"""update_project_model_and_add_billing

Revision ID: de11916c12eb
Revises: 6ec9a5e5971d
Create Date: 2025-11-25 15:37:49.845187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de11916c12eb'
down_revision: Union[str, Sequence[str], None] = '6ec9a5e5971d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('project_billings',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('project_id', sa.Integer(), nullable=True),
    # sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    # sa.Column('date', sa.Date(), nullable=True),
    # sa.Column('description', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('project_billings', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_project_billings_id'), ['id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('project_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimated_end_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_projects_client_id', 'clients', ['client_id'], ['id'])
        batch_op.drop_column('estimated_date')
        batch_op.drop_column('invoiced')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoiced', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimated_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint('fk_projects_client_id', type_='foreignkey')
        batch_op.drop_column('estimated_end_date')
        batch_op.drop_column('estimated_start_date')
        batch_op.drop_column('team_size')
        batch_op.drop_column('project_number')
        batch_op.drop_column('client_id')

    op.drop_index(op.f('ix_project_billings_id'), table_name='project_billings')
    op.drop_table('project_billings')

    # ### end Alembic commands ###
